### ISSUE TITLE
This algorithm can not run on my dataset. 

### ISSUE THREAD

**Issue by ningustc** [berkels/match-series#1]
Hi Berkels, 

I tried to use your code to simply process my experimental data, it seems the code fails. 

log:

reading reference image from: D:/sampledata/sample0000.dm4
reading template image from: D:/sampledata/sample0000.dm4
Created directory results/stage1/
Using templates images ---------------------------------------
D:/sampledata/sample0001.dm4
D:/sampledata/sample0002.dm4
D:/sampledata/sample0003.dm4
D:/sampledata/sample0004.dm4
D:/sampledata/sample0005.dm4
D:/sampledata/sample0006.dm4
D:/sampledata/sample0007.dm4
D:/sampledata/sample0008.dm4
D:/sampledata/sample0009.dm4
D:/sampledata/sample0010.dm4
D:/sampledata/sample0011.dm4
D:/sampledata/sample0012.dm4
D:/sampledata/sample0013.dm4
D:/sampledata/sample0014.dm4
--------------------------------------------------------------
Created directory results/stage1/0/

--------------------------------------------------------
Registration on level 0 started
--------------------------------------------------------

The par file content:

templateNamePattern D:/sampledata/sample%04d.dm4
templateNumOffset 0
templateNumStep 1
numTemplates 15
deformationModel 0
#templateSkipNums { 1 9 10 173 }

cropInput 0
cropStartX 512
cropStartY 512
dontResizeOrCropReference 0

preSmoothSigma 1

saveRefAndTempl 0

numExtraStages 2

saveDirectory results/

dontNormalizeInputImages 0
enhanceContrastSaturationPercentage 0.15
normalizeMinToZero 1

# lambda weights the deformation regularization term
lambda         200
# lambdaFactor scales lambda dependening on the current level: On level d, lambda is multiplied by pow ( lambdaFactor, stopLevel - d )
lambdaFactor   1

maxGDIterations 500
stopEpsilon 1e-6

startLevel 6
stopLevel 10
precisionLevel 10
refineStartLevel 10
refineStopLevel 10

checkboxWidth 16

resizeInput 0

dontAccumulateDeformation 0
reuseStage1Results 1
extraStagesLambdaFactor 0.1
useMedianAsNewTarget 1
calcInverseDeformation 0
skipStage1 0

saveNamedDeformedTemplates 1
saveNamedDeformedTemplatesUsingNearestNeighborInterpolation 1
saveNamedDeformedTemplatesExtendedWithMean 1
saveDeformedTemplates 1
saveNamedDeformedDMXTemplatesAsDMX 1

**Comment by berkels** [comment]
We resolved this long ago, but I forgot to update the issue accordingly. The parameters needed to be adjusted to the dataset.
