### ISSUE TITLE
Can you create a Github release?

### ISSUE THREAD

**Issue by jan-janssen** [berkels/match-series#2]
I currently try to create a conda package:
https://github.com/conda-forge/staged-recipes/pull/11956

To be able to install `match-series` with all the required dependencies as easy as:
```
conda install -c conda-forge match-series
```

So to be able to fix one version of `match-series` for future reference and to increase the reproducibility it would be great if you could create a Github release.

**Comment by berkels** [comment]
Making this available via conda is a great idea! I just created a GitHub release to support this.

**Comment by jan-janssen** [comment]
@berkels Should I add you as a maintainer?
