### ISSUE TITLE
Multithreaded or GPU?

### ISSUE THREAD

**Issue by mmw0909** [berkels/match-series#5]
Hi Dr. Berkels, Thanks for sharing your work. I am wondering if there is any plan to support multithreaded CPU implementation or GPU implementation? Thanks.

**Comment by din14970** [comment]
@zml941116 I'm attempting to re-implement the algorithm using python such that it would be multithreaded and then possibly use the GPU, mainly by trying to leverage numba, see https://github.com/din14970/pyMatchSeries/blob/testing/pymatchseries/implementation.py. @berkels helps out with the conceptual stuff but doesn't have much time for actual coding as far as I understand. Unfortunately I haven't had a lot of time myself recently to work on it so development has stalled. Feel free to contribute.

**Comment by mmw0909** [comment]
Hi Dr. Cautaerts, Thanks for your quick response. I may not be able to make any contribution due to my lack of knowledge in C++. I also notice there is an open issue discussing the development, thus I will close this. Looking forward to using the accelerated version when you have time to finish the development.

**Comment by din14970** [comment]
I also don't know any C++ which is why I'm using purely Python for my implementation; it is really entirely from scratch. If you know some python you might give it a shot. If you rely entirely on me, don't expect a solution within the next few months ;)
